services:
  app:
    build: .
    restart: always
    command: bash -c "
      python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000
      "
    depends_on:
      database:
        condition: service_healthy
    ports:
      - '80:8000'
  database:
    image: postgres:alpine
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=root
    expose:
      - 5432
  cache:
    image: redis:alpine
    expose:
      - 6379

volumes:
  db:
    driver: local